#FROM ghcr.io/windmill-labs/windmill:1.627.0
#FROM harbor-devops.devpos-hv.icsd.tsmc.com/base-prod/pled/oss/dockerhub/rophy/windmill:v1.627.0-1-g7dec1cc45
#FROM asia-east1-docker.pkg.dev/gpnr19prj0015isb-extl/gpae19afr0001isb/rophy/windmill:v1.627.0-1-g7dec1cc45
FROM rophy/windmill:v1.627.0-1-g7dec1cc45

RUN rm -rf /tmp/*

#RUN apt install -y php

#RUN apt-get update && \
#	apt-get upgrade -y php form-data && \
#	apt-get clean 